name: Wiki Issue
description: Find an issue with the wiki? Please describe it here!
title: "(Wiki) "
labels: Wiki Issue

body:
  - type: input
    id: link
    attributes:
      label: Please link to the page with an error
      placeholder: https://github.com/sstixrud/WeaponCore/wiki
  - type: textarea
    id: description
    attributes:
      label: Where is the issue, and what should be changed?
      description: Be descriptive!
      placeholder: Enter details here

## Please link to the page with an error:



## Where is the issue, and what should be changed?
